apiVersion: v1
kind: Pod
metadata:
 name: cncf-demo-coredns-build
spec:
 containers:
 - name: cncf-demo-coredns-build
   image: docker.io/containerops/cncf-demo-coredns:latest
   env:
   - name: CO_DATA
     value: "coredns=https://github.com/coredns/coredns.git action=build release=test.opshub.sh/containerops/cncf-demo/demo"
 restartPolicy: Never
