apiVersion: v1
kind: Pod
metadata:
 name: cncf-demo-prometheus-build
spec:
 containers:
 - name: cncf-demo-prometheus-build
   image: hub.opshub.sh/containerops/cncf-demo-prometheus:latest
   env:
   - name: CO_DATA
     value: "prometheus=https://github.com/prometheus/prometheus.git action=build release=hub.opshub.sh/containerops/cncf-demo/demo"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never
