# Copyright 2016 - 2017 Huawei Technologies Co., Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: cncnf/demo-for-cncf-ci
title: Demo For Cloud Native Computing Foundation CI Working Group
version: 12
tag: latest
timeout: 0
stages:
  - stage:
      type: start
      name: start
      title: Start
  - stage:
      type: normal
      name: k8s-test-build-release
      title: Build, Test and Publish the Kubernetes Binary
      sequencing: sequence # parallel or sequnce
      actions:
        - action:
            name: build-kubernetes
            title: Build Kubernetes
            jobs:
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=build
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=build
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=build
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=build
        - action:
            name: test-kubernetes
            title: Test Kubernetes
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=test
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=test
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=test
        - action:
            name: release-kubernetes
            title: Publish Kubernetes
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=release
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-kubernetes
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: kubernetes=https://github.com/kubernetes/kubernetes.git action=release
  - stage:
      type: normal
      name: prometheus-test-build-release
      title: Build, Test and Publish the Prometheus Binary
      sequencing: sequence
      actions:
        - action:
            name: build-prometheus
            title: Build Prometheus
            jobs:
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-prometheus
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: prometheus=https://github.com/prometheus/prometheus.git action=build
        - action:
            name: test-prometheus
            title: Test Prometheus
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-prometheus
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: prometheus=https://github.com/prometheus/prometheus.git action=test
        - action:
            name: release-prometheus
            title: Publish Prometheus
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-prometheus
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: prometheus=https://github.com/prometheus/prometheus.git action=release
  - stage:
      type: normal
      name: coredns-test-build-release
      title: Build, Test and Publish the CoreDNS Binary
      sequencing: sequence
      actions:
        - action:
            name: build-coredns
            title: Build CoreDNS
            jobs:
              - job:
                  type: component # component or service
                  endpoint: docker.io/containerops/cncf-demo-coredns
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: coredns=https://github.com/coredns/coredns.git action=build
        - action:
            name: test-coredns
            title: Test CoreDNS
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-coredns
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: coredns=https://github.com/coredns/coredns.git action=test
        - action:
            name: release-coredns
            title: Publish CoreDNS
            jobs:
              - job:
                  type: component
                  endpoint: docker.io/containerops/cncf-demo-coredns
                  resources:
                    cpu: 0
                    memory: 0
                  timeout: 0
                  environments:
                    - default: coredns=https://github.com/coredns/coredns.git action=release
  - stage:
        type: end
        name: end
        title: End
