# Copyright 2016 - 2017 Huawei Technologies Co., Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#<namespace>/<repository>/<flow>
uri: containerops/component/php-component-build-test
title: Component for php project with composer
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-composer-build
    title: Component, Building php project with composer
    sequencing: sequence
    actions:
      -
        name: build-composer
        title: Build php project with "composer"
        jobs:
          -
            type: component
            kubectl: composer-build.yaml
            endpoint: hub.opshub.sh/containerops/component-composer:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/TIGERB/easy-php.git action=install"
      -
        name: analysis-phploc
        title: Analysis php project with "phploc"
        jobs:
          -
            type: component
            kubectl: component-phploc.yaml
            endpoint: hub.opshub.sh/containerops/phploc:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/TIGERB/easy-php.git exclude=public"
      -
        name: analysis-phpcpd
        title: Analysis php project with "phpcpd"
        jobs:
          -
            type: component
            kubectl: component-phpcpd.yaml
            endpoint: hub.opshub.sh/containerops/phpcpd:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/TIGERB/easy-php.git"
      -
        name: analysis-phpmd
        title: Analysis php project with "phpmd"
        jobs:
          -
            type: component
            kubectl: component-phpmd.yaml
            endpoint: hub.opshub.sh/containerops/phpmd:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/TIGERB/easy-php.git"
  -
    type: end
    name: end
    title: End
