apiVersion: v1
kind: Pod
metadata:
 name: cncf-demo-kubernetes-test
spec:
 containers:
 - name: cncf-demo-kubernetes-test
   image: hub.opshub.sh/containerops/cncf-demo-kubernetes:latest
   env:
   - name: CO_DATA
     value: "kubernetes=https://github.com/kubernetes/kubernetes.git action=test release=hub.opshub.sh/containerops/cncf-demo/demo"
   resources:
     requests:
       cpu: 2
       memory: 8G
 restartPolicy: Never
